pipeline {
    agent any

    environment {
        DOCKERHUB_CREDS=credentials('dockerhub_creds')
        LC_ALL = "en_US.UTF-8"
        LANG    = "en_US.UTF-8"
        LANGUAGE = "en_US.UTF-8"
        GITHUB_SSH_CREDS=credentials('github_bigdata2024_itmo')
        MODELAPI_ENV = credentials('modelapi_env')
        DCOMPOSE_ENV = credentials('docker_compose_env')
    }

    stages {
        stage('Cloning github-repository'){
            steps{
                echo "====[STAGE1]===="
                cleanWs()
                sh "ssh-agent bash -c 'ssh-add $GITHUB_SSH_CREDS; git clone -b main git@github.com:Dzigen/BigData2024_ITMO_lab2.git'"
                sh 'cd BigData2024_ITMO_lab2/modelapi && dvc pull models/prod_model.pkl'
                sh 'cat ${MODELAPI_ENV} > BigData2024_ITMO_lab2/modelapi/.env'
                sh 'cat ${DCOMPOSE_ENV} > BigData2024_ITMO_lab2/.env'
            }
        }
        
        stage('Building ModelAPI-image') {
            steps {
                echo "====[STAGE2]===="
                sh 'docker --version'
                sh 'echo  $DOCKERHUB_CREDS_PSW | docker login -u $DOCKERHUB_CREDS_USR --password-stdin'
                sh 'docker pull dzigen/base_model_api:v1'
                sh 'cd BigData2024_ITMO_lab2 && docker-compose build --no-cache modelapi'
            }
        }

        stage('Test run of ModelAPI-image') {
            steps {
                echo "====[STAGE3]===="
                sh 'cd BigData2024_ITMO_lab2/ && docker-compose up -d modelapi'
            }
        }

        stage('Push ModelAPI-image to DockerHub') {
            steps {
                echo "====[STAGE4]===="
                sh 'docker push dzigen/model_api:v1'
            }
        }
    }

    post {
        always {
            sh 'docker stop modelapi_cntname && docker rm modelapi_cntname'
            sh 'docker logout'
            cleanWs()
        }
    }
}        